name: Fontend Deploy

on:
  push:
    branches:
      - main
    paths:
      - "frontend/**"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Frontend CI/CD

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Setup Node.Js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Navigate to Frontend
        run: cd frontend

      - name: Install dependencies
        run: npm install 
        working-directory: frontend
      
      - name: Build Project
        run: npm run build
        working-directory: frontend

      - name: Deploy to Cpanel via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: fontend/dist/
          server-dir: /